In [9]:
import numpy as np

In [10]:
i = [[0,  0,  0, 0],
     [0,  1,  2, 0],
     [0,  4,  9, 0],
     [0, 14, 15, 0],
     [0, 30, 50, 0],
     [0,  0,  0, 0]]
I = np.array(i)

In [11]:
print(i)
print(I)

[[0, 0, 0, 0], [0, 1, 2, 0], [0, 4, 9, 0], [0, 14, 15, 0], [0, 30, 50, 0], [0, 0, 0, 0]]
[[ 0  0  0  0]
 [ 0  1  2  0]
 [ 0  4  9  0]
 [ 0 14 15  0]
 [ 0 30 50  0]
 [ 0  0  0  0]]


In [12]:
g = np.gradient(I)

In [13]:
#        The gradients are returned in Numpy axis order (row, column, ...) therefore:
#            results[0] = Y gradient
#            results[1] = X gradient
gradient_y = g[0]
gradient_x = g[1]

In [14]:
print (gradient_x)

[[  0.    0.    0.    0. ]
 [  1.    1.   -0.5  -2. ]
 [  4.    4.5  -2.   -9. ]
 [ 14.    7.5  -7.  -15. ]
 [ 30.   25.  -15.  -50. ]
 [  0.    0.    0.    0. ]]


In [15]:
print(gradient_y)

[[  0.    1.    2.    0. ]
 [  0.    2.    4.5   0. ]
 [  0.    6.5   6.5   0. ]
 [  0.   13.   20.5   0. ]
 [  0.   -7.   -7.5   0. ]
 [  0.  -30.  -50.    0. ]]


In [8]:
gradient_x[3,1]

7.5