In [1]:
import numpy as np
from enum import Enum
from typing import List

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
forward_roll = np.roll(a, 1, -1)
forward_roll

array([[3, 1, 2],
       [6, 4, 5],
       [9, 7, 8]])

In [4]:
first_column = a[:,0]
print(first_column)

[1 4 7]


In [5]:
forward_roll[:,0] = first_column
print(a)
print()
print(forward_roll)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 1 2]
 [4 4 5]
 [7 7 8]]


In [6]:
a - forward_roll

array([[0, 1, 1],
       [0, 1, 1],
       [0, 1, 1]])

In [7]:
class FiniteDifference(Enum):
    """
    A class representing the types of finite differences.
    """
    Forward = 1,
    Backward = 2

In [8]:
    def difference_x(a: np.ndarray, direction:FiniteDifference) -> np.ndarray:
        """
        Calculates the finite dfferences along the X axis.
        Parameters
        ----------
        a
            The array from which to calculate the finite differences.
        direction
            The direction of the finite difference (forward, backward).
        Returns
        -------
        An ndarray containing the finite differences.
        """
        (rows, columns) = a.shape
        difference = np.zeros((rows, columns))

        if direction == FiniteDifference.Forward:
            first_offset  = +1
            second_offset =  0
        if direction == FiniteDifference.Backward:
            first_offset  =  0
            second_offset = -1

        for row in range (rows):
            for column in range(columns):
                if (direction == FiniteDifference.Backward) and (column == 0):
                    continue
                if (direction == FiniteDifference.Forward) and (column == (columns - 1)):
                    continue
                difference[row, column] = a[row, column + first_offset] - a[row, column + second_offset]

        print("Array")
        print (a)
        print("")

        print("Loop")
        print (difference)
        print("")
                
        difference_optimized = difference_x_optimized(a, direction)                
        print("Roll")
        print (difference_optimized)
        print("")
        
        print (f"Loop == Roll: {np.array_equal(difference, difference_optimized)}")

        return difference


In [9]:
    def difference_x_optimized(a: np.ndarray, direction:FiniteDifference) -> np.ndarray:
        """
        Calculates the finite dfferences along the X axis.
        Parameters
        ----------
        a
            The array from which to calculate the finite differences.
        direction
            The direction of the finite difference (forward, backward).
        Returns
        -------
        An ndarray containing the finite differences.
        """
        (_, columns) = a.shape
        if direction == FiniteDifference.Forward:
            shift = -1
            duplicated_column = columns -1 
        if direction == FiniteDifference.Backward:
            shift = +1
            duplicated_column = 0

        a_prime = np.roll(a, shift, 1)
        a_prime[:, duplicated_column] = a[:, duplicated_column]
        
        print("Array Prime")
        print (a_prime)
        print("")

        f_plus_delta = a_prime if direction == FiniteDifference.Forward else a
        f = a if direction == FiniteDifference.Forward else a_prime
        
        difference = f_plus_delta - f
        return difference

In [10]:
difference = difference_x(a, direction=FiniteDifference.Forward)

Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Loop
[[1. 1. 0.]
 [1. 1. 0.]
 [1. 1. 0.]]

Array Prime
[[2 3 3]
 [5 6 6]
 [8 9 9]]

Roll
[[1 1 0]
 [1 1 0]
 [1 1 0]]

Loop == Roll: True


In [11]:
difference = difference_x(a, direction=FiniteDifference.Backward)

Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Loop
[[0. 1. 1.]
 [0. 1. 1.]
 [0. 1. 1.]]

Array Prime
[[1 1 2]
 [4 4 5]
 [7 7 8]]

Roll
[[0 1 1]
 [0 1 1]
 [0 1 1]]

Loop == Roll: True
