In [9]:
import numpy as np
from enum import Enum
from typing import List

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
pad = 2
width = 3
height = 4

In [20]:
b = np.zeros((height + (2 * pad), width + (2 * pad)))

In [21]:
b

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [22]:
b[pad:(pad + height), pad:(pad + width)] = a
b

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  0.,  0.],
       [ 0.,  0.,  4.,  5.,  6.,  0.,  0.],
       [ 0.,  0.,  7.,  8.,  9.,  0.,  0.],
       [ 0.,  0., 10., 11., 12.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [23]:
b[0:pad, pad:pad + width] = a[0,:]
b[pad + height:, pad:pad + width] = a[height - 1,:]

b[pad:pad+height, 0:pad] = a[:,0:1]
b[pad:pad+height, pad + width:] = a[:,width - 1:width]
b

array([[ 0.,  0.,  1.,  2.,  3.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  0.,  0.],
       [ 1.,  1.,  1.,  2.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  5.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  8.,  9.,  9.,  9.],
       [10., 10., 10., 11., 12., 12., 12.],
       [ 0.,  0., 10., 11., 12.,  0.,  0.],
       [ 0.,  0., 10., 11., 12.,  0.,  0.]])

In [16]:
import numpy as np
image = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

height = image.shape[0]
width = image.shape[1]

pad = 2
padded_image = np.zeros((height + (2 * pad), width + (2 * pad)))
padded_image[pad:(height + pad), pad:(width + pad), ] = image

# create margins; replicate edges of source ('constant' mode)
padded_image[0:pad, pad:pad + width] = image[0,:]
padded_image[pad + height:, pad:pad + width] = image[height - 1,:]

padded_image[pad:pad+height, 0:pad] = image[:,0:1]
padded_image[pad:pad+height, pad + width:] = image[:,width - 1:width]

# extract original
padded_result = padded_image
result = np.zeros((width, height))
result = padded_result[pad:(height + pad), pad:(width + pad)]

image
padded_image
#padded_result
#result

array([[ 0.,  0.,  1.,  2.,  3.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  0.,  0.],
       [ 1.,  1.,  1.,  2.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  5.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  8.,  9.,  9.,  9.],
       [10., 10., 10., 11., 12., 12., 12.],
       [ 0.,  0., 10., 11., 12.,  0.,  0.],
       [ 0.,  0., 10., 11., 12.,  0.,  0.]])